function __byron_alias --argument-names name body
    set -l escaped_name (string escape -- $name)
    set -l escaped_body (string escape -- $body)
    set -l escaped_description (string escape -- "alias $name=$body")

    printf 'function %s --wraps %s --description %s; %s $argv; end\n' \
        $escaped_name \
        $escaped_body \
        $escaped_description \
        $body | source
end

__byron_alias g 'git'
__byron_alias ga 'git add'
__byron_alias gaa 'git add --all'
__byron_alias gam 'git am'
__byron_alias gama 'git am --abort'
__byron_alias gamc 'git am --continue'
__byron_alias gams 'git am --skip'
__byron_alias gamscp 'git am --show-current-patch'
__byron_alias gap 'git apply'
__byron_alias gapa 'git add --patch'
__byron_alias gapt 'git apply --3way'
__byron_alias gau 'git add --update'
__byron_alias gav 'git add --verbose'
__byron_alias gb 'git branch'
__byron_alias gbD 'git branch --delete --force'
__byron_alias gba 'git branch --all'
__byron_alias gbd 'git branch --delete'
__byron_alias gbl 'git blame -w'
__byron_alias gbm 'git branch --move'
__byron_alias gbnm 'git branch --no-merged'
__byron_alias gbr 'git branch --remote'
__byron_alias gbs 'git bisect'
__byron_alias gbsb 'git bisect bad'
__byron_alias gbsg 'git bisect good'
__byron_alias gbsn 'git bisect new'
__byron_alias gbso 'git bisect old'
__byron_alias gbsr 'git bisect reset'
__byron_alias gbss 'git bisect start'
__byron_alias gc 'git commit --verbose'
__byron_alias 'gc!' 'git commit --verbose --amend'
__byron_alias gcB 'git checkout -B'
__byron_alias gca 'git commit --verbose --all'
__byron_alias 'gca!' 'git commit --verbose --all --amend'
__byron_alias gcam 'git commit --all --message'
__byron_alias 'gcan!' 'git commit --verbose --all --no-edit --amend'
__byron_alias 'gcann!' 'git commit --verbose --all --date=now --no-edit --amend'
__byron_alias 'gcans!' 'git commit --verbose --all --signoff --no-edit --amend'
__byron_alias gcas 'git commit --all --signoff'
__byron_alias gcasm 'git commit --all --signoff --message'
__byron_alias gcb 'git checkout -b'
__byron_alias gcd 'git checkout (git_develop_branch)'
__byron_alias gcf 'git config --list'
__byron_alias gcfu 'git commit --fixup'
__byron_alias gcl 'git clone --recurse-submodules'
__byron_alias gclean 'git clean --interactive -d'
__byron_alias gclf 'git clone --recursive --shallow-submodules --filter=blob:none --also-filter-submodules'
__byron_alias gcm 'git checkout (git_main_branch)'
__byron_alias gcmsg 'git commit --message'
__byron_alias gcn 'git commit --verbose --no-edit'
__byron_alias 'gcn!' 'git commit --verbose --no-edit --amend'
__byron_alias gco 'git checkout'
__byron_alias gcor 'git checkout --recurse-submodules'
__byron_alias gcount 'git shortlog --summary --numbered'
__byron_alias gcp 'git cherry-pick'
__byron_alias gcpa 'git cherry-pick --abort'
__byron_alias gcpc 'git cherry-pick --continue'
__byron_alias gcs 'git commit --gpg-sign'
__byron_alias gcsm 'git commit --signoff --message'
__byron_alias gcss 'git commit --gpg-sign --signoff'
__byron_alias gcssm 'git commit --gpg-sign --signoff --message'
__byron_alias gd 'git diff'
__byron_alias gdca 'git diff --cached'
__byron_alias gdct 'git describe --tags (git rev-list --tags --max-count=1)'
__byron_alias gdcw 'git diff --cached --word-diff'
__byron_alias gds 'git diff --staged'
__byron_alias gdt 'git diff-tree --no-commit-id --name-only -r'
__byron_alias gdup 'git diff @{upstream}'
__byron_alias gdw 'git diff --word-diff'
__byron_alias gf 'git fetch'
__byron_alias gfa 'git fetch --all --tags --prune --jobs=10'
__byron_alias gfg 'git ls-files | grep'
__byron_alias gfo 'git fetch origin'
__byron_alias gg 'git gui citool'
__byron_alias gga 'git gui citool --amend'
__byron_alias ggpull 'git pull origin (git_current_branch)'
__byron_alias ggpush 'git push origin (git_current_branch)'
__byron_alias ggsup 'git branch --set-upstream-to=origin/(git_current_branch)'
__byron_alias ghh 'git help'
__byron_alias gignore 'git update-index --assume-unchanged'
__byron_alias gignored 'git ls-files -v | grep "^[[:lower:]]"'
__byron_alias git-svn-dcommit-push 'git svn dcommit; and git push github (git_main_branch):svntrunk'
__byron_alias gl 'git pull'
__byron_alias glf 'git pull --ff-only'
__byron_alias glg 'git log --stat'
__byron_alias glgg 'git log --graph'
__byron_alias glgga 'git log --graph --decorate --all'
__byron_alias glgm 'git log --graph --max-count=10'
__byron_alias glgp 'git log --stat --patch'
__byron_alias glo 'git log --oneline --decorate'
__byron_alias glod 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset"'
__byron_alias glods 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset" --date=short'
__byron_alias glog 'git log --oneline --decorate --graph'
__byron_alias gloga 'git log --oneline --decorate --graph --all'
__byron_alias glol 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset"'
__byron_alias glola 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset" --all'
__byron_alias glols 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset" --stat'
__byron_alias gluc 'git pull upstream (git_current_branch)'
__byron_alias glum 'git pull upstream (git_main_branch)'
__byron_alias gm 'git merge'
__byron_alias gma 'git merge --abort'
__byron_alias gmc 'git merge --continue'
__byron_alias gmff 'git merge --ff-only'
__byron_alias gmom 'git merge origin/(git_main_branch)'
__byron_alias gms 'git merge --squash'
__byron_alias gmtl 'git mergetool --no-prompt'
__byron_alias gmtlvim 'git mergetool --no-prompt --tool=vimdiff'
__byron_alias gmum 'git merge upstream/(git_main_branch)'
__byron_alias gp 'git push'
__byron_alias gpd 'git push --dry-run'
__byron_alias gpf 'git push --force-with-lease --force-if-includes'
__byron_alias 'gpf!' 'git push --force'
__byron_alias gpoat 'git push origin --all; and git push origin --tags'
__byron_alias gpod 'git push origin --delete'
__byron_alias gpr 'git pull --rebase'
__byron_alias gpra 'git pull --rebase --autostash'
__byron_alias gprav 'git pull --rebase --autostash -v'
__byron_alias gpristine 'git reset --hard; and git clean --force -dfx'
__byron_alias gprom 'git pull --rebase origin (git_main_branch)'
__byron_alias gpromi 'git pull --rebase=interactive origin (git_main_branch)'
__byron_alias gprum 'git pull --rebase upstream (git_main_branch)'
__byron_alias gprumi 'git pull --rebase=interactive upstream (git_main_branch)'
__byron_alias gprv 'git pull --rebase -v'
__byron_alias gpsup 'git push --set-upstream origin (git_current_branch)'
__byron_alias gpsupf 'git push --set-upstream origin (git_current_branch) --force-with-lease --force-if-includes'
__byron_alias gpu 'git push upstream'
__byron_alias gpv 'git push --verbose'
__byron_alias gr 'git remote'
__byron_alias gra 'git remote add'
__byron_alias grb 'git rebase'
__byron_alias grba 'git rebase --abort'
__byron_alias grbc 'git rebase --continue'
__byron_alias grbd 'git rebase (git_develop_branch)'
__byron_alias grbi 'git rebase --interactive'
__byron_alias grbm 'git rebase (git_main_branch)'
__byron_alias grbo 'git rebase --onto'
__byron_alias grbom 'git rebase origin/(git_main_branch)'
__byron_alias grbs 'git rebase --skip'
__byron_alias grbum 'git rebase upstream/(git_main_branch)'
__byron_alias grev 'git revert'
__byron_alias greva 'git revert --abort'
__byron_alias grevc 'git revert --continue'
__byron_alias grf 'git reflog'
__byron_alias grh 'git reset'
__byron_alias grhh 'git reset --hard'
__byron_alias grhk 'git reset --keep'
__byron_alias grhs 'git reset --soft'
__byron_alias grm 'git rm'
__byron_alias grmc 'git rm --cached'
__byron_alias grmv 'git remote rename'
__byron_alias groh 'git reset origin/(git_current_branch) --hard'
__byron_alias grrm 'git remote remove'
__byron_alias grs 'git restore'
__byron_alias grset 'git remote set-url'
__byron_alias grss 'git restore --source'
__byron_alias grst 'git restore --staged'
__byron_alias gru 'git reset --'
__byron_alias grup 'git remote update'
__byron_alias grv 'git remote --verbose'
__byron_alias gsb 'git status --short --branch'
__byron_alias gsd 'git svn dcommit'
__byron_alias gsh 'git show'
__byron_alias gsi 'git submodule init'
__byron_alias gsps 'git show --pretty=short --show-signature'
__byron_alias gsr 'git svn rebase'
__byron_alias gss 'git status --short'
__byron_alias gst 'git status'
__byron_alias gsta 'git stash push'
__byron_alias gstaa 'git stash apply'
__byron_alias gstall 'git stash --all'
__byron_alias gstc 'git stash clear'
__byron_alias gstd 'git stash drop'
__byron_alias gstl 'git stash list'
__byron_alias gstp 'git stash pop'
__byron_alias gsts 'git stash show --patch'
__byron_alias gsu 'git submodule update'
__byron_alias gsw 'git switch'
__byron_alias gswc 'git switch --create'
__byron_alias gswd 'git switch (git_develop_branch)'
__byron_alias gswm 'git switch (git_main_branch)'
__byron_alias gta 'git tag --annotate'
__byron_alias gts 'git tag --sign'
__byron_alias gtv 'git tag | sort -V'
__byron_alias gunignore 'git update-index --no-assume-unchanged'
__byron_alias gunwip 'git rev-list --max-count=1 --format="%s" HEAD | grep -q "\--wip--"; and git reset HEAD~1'
__byron_alias gwch 'git log --patch --abbrev-commit --pretty=medium --raw'
__byron_alias gwip 'git add -A; git rm (git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign --message "--wip-- [skip ci]"'
__byron_alias gwipe 'git reset --hard; and git clean --force -df'
__byron_alias gwt 'git worktree'
__byron_alias gwta 'git worktree add'
__byron_alias gwtls 'git worktree list'
__byron_alias gwtmv 'git worktree move'
__byron_alias gwtrm 'git worktree remove'
__byron_alias sgg 'stg goto'
__byron_alias sgr 'stg refresh'
__byron_alias sgri 'stg refresh --index'
__byron_alias sgs 'stg series -IPd'
__byron_alias cdd 'cd-repo'
__byron_alias wts 'wt switch'
__byron_alias orc 'cd-repo-corpus'
__byron_alias l 'eza -abgl'
__byron_alias lla 'eza -abgl'
__byron_alias cat 'bat'
__byron_alias tix 'tig'

functions --erase __byron_alias
