execute pathogen#infect()

filetype plugin indent on
set noswapfile
syntax on

autocmd FileType yaml setlocal shiftwidth=2 tabstop=2
autocmd FileType sh setlocal shiftwidth=2 tabstop=2

set background=dark
" colorscheme solarized   " Enable solarized colorscheme

set number              " Show line numbers
set relativenumber
" set showbreak=+++       " Wrap-broken line prefix
set nowrap              " no line wrapping
set textwidth=100	" Line wrap (number of cols)
set formatoptions-=t    " Don't auto-break lines
set showmatch           " Highlight matching brace
" set spell               " Enable spell-checking
set spellfile=~/.vim/spell/en.utf-8.add
set visualbell          " Use visual bell (no beeping)

" set hlsearch            " Highlight all search results
set smartcase           " Enable smart-case search
set ignorecase          " Always case-insensitive
set incsearch           " Searches for strings incrementally

set autoindent          " Auto-indent new lines
set expandtab           " Use spaces instead of tabs
set shiftwidth=4        " Number of auto-indent spaces
set smartindent         " Enable smart-indent
set smarttab            " Enable smart-tabs
set softtabstop=4       " Number of spaces per Tab

set ruler               " Show row and column ruler information

set undolevels=1000             " Number of undo levels
set backspace=indent,eol,start  " Backspace behaviour

" List whitespace characters
" set listchars=eol:$,tab:>·,trail:~,extends:>,precedes:<,space:·
" set list
"
set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
