#true Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(tig git macos wd docker kubectl rust brew)

# export MANPATH="/usr/local/man:$MANPATH"
#
source $ZSH/oh-my-zsh.sh

export PATH="$HOME/.npm-global/bin:$PATH"
source ~/.profile || { echo "Put at least your GIT_(AUTHOR|COMMITTER)_(NAME|EMAIL) as exports into ~/.profile"; }

# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.skim.zsh ] && source ~/.skim.zsh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
export EDITOR='hx'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
alias reload="exec \$SHELL"
alias tmux='tmux -u'
alias tma='tmux attach'
alias tmn='tmux new-session \; rename-window project \; new-window -n project-test\; new-window -n util \; new-window -n stats \; new-window -n criner \; attach'


# export TERM=screen.xterm-new
export TERM=xterm-256color

# Git Aliases
alias glf="git pull --ff-only"
function gua () {
    find . -type d -name .git -maxdepth 2 | while read dir; do (cd $(dirname $dir) && git pull --rebase); done
}
function assh () {
    eval `ssh-agent`;
    ssh-add
}


function code {
    if [[ $# = 0 ]]
    then
        open -a "Visual Studio Code"
    else
        local argPath="$1"
        [[ $1 = /* ]] && argPath="$1" || argPath="$PWD/${1#./}"
        open -a "Visual Studio Code" "$argPath"
    fi
}


setopt HIST_IGNORE_SPACE

alias la='exa -abgl'
alias l='exa -abgl'
alias ll='exa -bgl'

alias syv="sy vault"

# viewing
alias viewy="view - -c 'set syntax=yaml'"
alias viewj="view - -c 'set syntax=json'"

alias btop="battop"

alias j="just"
alias jl="just --list"

# task queue
# cargo install pueue
alias pup="pueued -d"
alias pdo="pueue shutdown"
alias pad="pueue add --"
alias pst="pueue status"
alias pcl="pueue clean"
alias pq="pueue"

# source ~/.nix-profile/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

function select-repo() {
    local root=~/dev
    echo -n $root/
    {
        cd $root
        ein --quiet t find
    } | sk -q "$1"
}

function cd-repo() {
    cd "$(select-repo $@)"
}

alias or="cd-repo"

function select-corpus() {
    local root=/Volumes/gix-corpus/github.com
    echo -n $root/
    {
        cd $root
        ein --quiet t find
    } | sk -q "$1"
}

function cd-repo-corpus() {
    cd "$(select-corpus $@)"
}

# First and only argument is the desired term title
function rename_title {
  echo "\x1b]1337;SetUserVar=panetitle=$(echo -n $1 | base64)\x07"
}

alias orc="cd-repo-corpus"

export BAT_THEME="TwoDark" 
alias cat="bat --theme TwoDark"

eval "$(navi widget zsh)"
alias navi="navi --finder skim"

alias sgs="stg series"
alias sgr="stg refresh"
alias sgri="stg refresh --index"
alias sgg="stg goto"

eval "$(atuin init zsh)"
eval "$(starship init zsh)"
eval "$(rtx activate zsh)" && eval "$(rtx complete --shell zsh)"

export PATH="/opt/homebrew/opt/awscli@1/bin:/Applications/WezTerm.app/Contents/MacOS:$PATH"

# User configuration
#
eval "$(brew shellenv)"
fpath=($HOMEBREW_PREFIX/share/zsh/site-functions $fpath)


export HOMEBREW_NO_ANALYTICS=1
