"$schema" = "https://starship.rs/config-schema.json"
format = "$all"

[git_branch]
format = "on [$symbol$branch(:$remote_name/$remote_branch)]($style) "
always_show_remote = false

[git_status]
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇕⇡$ahead_count⇣$behind_count"
up_to_date = "≡"

[buf]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[cpp]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[fennel]
disabled = true

[fortran]
disabled = true

[gleam]
disabled = true

[golang]
disabled = true

[gradle]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
disabled = true

[meson]
disabled = true

[mojo]
disabled = true

[nim]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[odin]
disabled = true

[opa]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[quarto]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[rlang]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[solidity]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[typst]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[xmake]
disabled = true

[zig]
disabled = true
